### ISSUE TITLE
`--format json` option should print pure JSON

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#1319] opened 2023-08-31 18:40 UTC
**Bug Description**

ricardo
 Is this mix of text and json expected when I run with --format=json ?

```
root@ip-172-16-10-111:/tmp# ./preflight --interactive=false --format=json ./helmvm-preflight.yaml
[Port 22] Running collector...
[Port 23] Running collector...
[Port 24] Running collector...
{
  "pass": [
    {
      "title": "Port 23",
      "message": "Port 23 is available"
    },
    {
      "title": "Port 24",
      "message": "Port 24 is available"
    }
  ],
  "warn": [
    {
      "title": "Port 22",
      "message": "Another process was already listening on port 22."
    }
  ]
}
```

**Expected Behavior**

when `--format` options are used, logging should be emitted to stderr and not stdout, or omitted completely;  that way the user can redirect output from the application without conflicting non-JSON strings

Include a description of the expected behaviour here.

```
$ ./preflights --interactive=false --format=json ./spec.yaml
{
  "pass": [
    {
      "title": "Port 23",
      "message": "Port 23 is available"
    },
    {
      "title": "Port 24",
      "message": "Port 24 is available"
    }
  ],
  "warn": [
    {
      "title": "Port 22",
      "message": "Another process was already listening on port 22."
    }
  ]
}
```

```
$ ./preflights --interactive=false --format=json ./spec.yaml 2>/dev/null > ./output.json
```

**Comment by ricardomaraschini** [comment] 2023-09-01 10:41
For what it is worth I just found out that these lines are already printed to stderr:

```
[Port 22] Running collector...
[Port 23] Running collector...
[Port 24] Running collector...
```

**Comment by arcolife** [comment] 2023-09-04 06:58
Took a look to try to reproduce:

```sh
# ./bin/preflight --interactive=false --format=json examples/preflight/text-analyze.yaml
name: cluster-resources    status: running         completed: 0    total: 3   
name: cluster-resources    status: completed       completed: 1    total: 3   
name: data                 status: running         completed: 1    total: 3   
name: data                 status: completed       completed: 2    total: 3   
name: cluster-info         status: running         completed: 2    total: 3   
name: cluster-info         status: completed       completed: 3    total: 3   
{
  "fail": [
    {
      "title": "Replica Count",
      "message": "That's not enough replicas!"
    }
  ]
}
```

and then

```sh
# ./bin/preflight --interactive=false --format=json examples/preflight/text-analyze.yaml 2>/dev/null
{
  "fail": [
    {
      "title": "Replica Count",
      "message": "That's not enough replicas!"
    }
  ]
}

# ./bin/preflight --interactive=false --format=json examples/preflight/node-resources.yaml 2>/dev/null   > ~/sample.json
```

Those work fine? cc/ @xavpaice 

Edit: changes for this were introduced way back in https://github.com/replicatedhq/troubleshoot/issues/906#issuecomment-1377897156

**Comment by xavpaice** [comment] 2023-09-04 07:09
Looks like this is working as intended, closing.

**Closed as completed by xavpaice** 2023-09-04 07:09 UTC
Labels: type::bug, good first issue, bug::normal
