### ISSUE TITLE
Preflight checks are returning many results instead of one 

### ISSUE THREAD

**Issue by camilamacedo86** [replicatedhq/troubleshoot#1089] opened 2023-03-31 17:45 UTC
**Bug Description**

I would expected to have 1 success result when I am have a lot of them:

![Screenshot 2023-06-01 at 10 35 07](https://github.com/replicatedhq/troubleshoot/assets/7708031/848fb2f2-dd4d-4961-925f-d25cdec9f42b)

[kurl-builtin-oncluster-results-2023-03-31T17_42_31.txt](https://github.com/replicatedhq/troubleshoot/files/11124569/kurl-builtin-oncluster-results-2023-03-31T17_42_31.txt)

**Expected Behavior**

See only once : 

> Check PASS
> Title: Check for CNI 'not ready' messages
> Message: CNI is initialized

**Steps To Reproduce**

Run the following the spec with preflight in a k8s cluster:

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: kurl-builtin-oncluster
spec:
  collectors:
    - run:
        collectorName: journalctl-kubelet
        image: busybox:1
        command: ["journalctl"]
        args: ["-u", "kubelet", "--no-pager", "-S", "7 days ago"]
  analyzers:
    - textAnalyze:
        checkName: "Check for CNI 'not ready' messages"
        file: run/journalctl-kubelet/journalctl-kubelet.logs
        ignoreIfNoFiles: true
        regex: "Container runtime network not ready.*cni plugin not initialized"
        outcomes:
          - pass:
              when: "false"
              message: "CNI is initialized"
          - fail:
              when: "true"
              message: "CNI plugin not initialized: there may be a problem with the CNI configuration on the host, check /etc/cni/net.d/*.conflist against a known good configuration"

```

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.
- Operating system
- Operating system version
- Other details that might be helpful in diagnosing the problem

**Comment by xavpaice** [comment] 2023-05-17 10:44
Probably need a bit more info here - the busybox image doesn't have journalctl so the pod doesn't actually start.

The same spec run as a support bundle doesn't produce any analyzer results at all, likely because the file doesn't exist in the bundle.  What we need to identify is what is causing the multiple results in preflight, when there's no actual result from the pod run.

For this particular check, I think what you're looking for is the host collector, rather than in-cluster collector, for the kubelet logs.

Would love to know if there's another reproducer we can see?

**Comment by xavpaice** [comment] 2023-05-17 10:57
A very unhelpful reproducer (but a reproducer all the same):

Environment: Ubuntu 2204, kURL cluster, run preflight on the host itself.

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: kurl-builtin-oncluster
spec:
  collectors:
    - run:
        collectorName: journalctl-kubelet
        image: busybox:1
        command: ["echo"]
        args: ["Something"]
  analyzers:
    - textAnalyze:
        checkName: "Check for CNI 'not ready' messages"
        file: run/journalctl-kubelet/journalctl-kubelet.logs
        ignoreIfNoFiles: true
        regex: "Container runtime network not ready.*cni plugin not initialized"
        outcomes:
          - pass:
              when: "false"
              message: "CNI is initialized"
          - fail:
              when: "true"
              message: "CNI plugin not initialized: there may be a problem with the CNI configuration on the host, check /etc/cni/net.d/*.conflist against a known good configuration"
```

**Comment by xavpaice** [comment] 2023-05-22 05:46
Note: in the `textAnalyze` analyzer, the `file` parameter should actually be `fileName`.  Making that change, and everything works fine.

What was happening otherwise is that because `fileName` is not specified, it's "", and therefore all files collected match - the analyzer ran for every file and produced a result for each one.

Since I cannot reproduce with a valid spec, I'll close this one.

**Comment by camilamacedo86** [comment] 2023-06-01 07:00
HI @xavpaice,

I still facing the issue see:
1 - I installed it via : curl https://krew.sh/preflight | bash

```sh
~$ kubectl preflight version
Replicated Preflight 0.65.0
```

2 - I am using ubuntu 20.04
3 - I am running the spec:

```
$ cat preflight.yaml 
# https://kurl.sh/docs/install-with-kurl/system-requirements
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: kurl-builtin-oncluster
spec:
  collectors:
    - clusterResources: {}
  hostCollectors:    
    - run:
        collectorName: journalctl-kubelet
        command: [ "journalctl" ]
        args: [ "-u", "kubelet", "--no-pager", "-S", "7 days ago" ]
  analyzers:
    - nodeResources:
        checkName: Node status check
        outcomes:
          - fail:
              when: "nodeCondition(Ready) == False"
              message: "Not all nodes are online."
          - fail:
              when: "nodeCondition(Ready) == Unknown"
              message: "Not all nodes are online."
          - pass:
              message: "All nodes are online."
    - textAnalyze:
        checkName: "Check for CNI 'not ready' messages"
        file: run/journalctl-kubelet/journalctl-kubelet.logs
        ignoreIfNoFiles: true
        regex: "Container runtime network not ready.*cni plugin not initialized"
        outcomes:
          - pass:
              when: "false"
              message: "CNI is initialized"
          - fail:
              when: "true"
              message: "CNI plugin not initialized: there may be a problem with the CNI configuration on the host, check /etc/cni/net.d/*.conflist against a known good configuration"
```
See the results duplicated:

![Screenshot 2023-06-01 at 08 00 18](https://github.com/replicatedhq/troubleshoot/assets/7708031/5550cc21-1fac-4a08-9cce-1ede4f64c6dc)

Also, see that by using your spec: https://github.com/replicatedhq/troubleshoot/issues/1089#issuecomment-1551179337
The values either are showing duplicated:

![Screenshot 2023-06-01 at 08 01 54](https://github.com/replicatedhq/troubleshoot/assets/7708031/101958dd-ecee-4337-9f08-ed7f1817e0f6)

 
@xavpaice can you please help know what I am doing wrong if the issue is not in the tool?

**Comment by xavpaice** [comment] 2023-06-22 05:07
Analysers need to have the `fileName` parameter.  Without that, every file that is found will be selected, and the analyzer will run for every file it processes, hence the multiple results.

I'll close this, it's an invalid spec rather than a bug.

**Closed as not planned by xavpaice** 2023-06-22 05:07 UTC
